version: "3"
networks:
  app-tier:
    driver: bridge
services:
  php:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    depends_on:
      - mysql
      - redis
    networks:
      - app-tier
    ports:
      - ${LOCAL_APP_PORT}:9000
    volumes:
      - .:/srv/app
    links:
      - mysql:mysql
      - redis:redis
  phpunit:
    container_name: ${CONTAINER_NAME}-phpunit
    build:
      context: .
      dockerfile: .docker/phpunit/Dockerfile
    depends_on:
      - mysql
      - redis
    networks:
      - app-tier
    ports:
      - ${LOCAL_PHPUNIT_PORT}:9000
    volumes:
      - .:/srv/app
    links:
      - mysql:mysql
      - redis:redis
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-tier
    depends_on:
      - php
    ports:
      - ${LOCAL_NGINX_PORT}:80
    volumes:
      - .:/srv/app
  mysql:
    container_name: ${CONTAINER_NAME}-mysql
    image: library/mysql:8.0.19
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=mysql-docker
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=password
    volumes:
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./backups/mysql:/backups/mysql
  mysql-test:
    container_name: ${CONTAINER_NAME}-mysql-test
    image: library/mysql:8.0.19
    tmpfs: /var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=mysql-docker
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=password
    volumes:
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
  redis:
    container_name: ${CONTAINER_NAME}-redis
    image: library/redis:5.0.9
    ports:
      - ${LOCAL_REDIS_PORT}:6379
    networks:
      - app-tier
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    networks:
      - app-tier
    container_name: ${CONTAINER_NAME}-selenium-hub
  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    networks:
      - app-tier
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
